# Generated by Django 5.0.1 on 2024-02-13 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='doctor1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fname', models.CharField(max_length=60)),
                ('Lname', models.CharField(max_length=60)),
                ('Age', models.IntegerField()),
                ('Adress', models.CharField(max_length=60)),
                ('Email', models.EmailField(max_length=254)),
                ('Experiance', models.IntegerField()),
            ],
        ),
    ]
